<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE urlset [
	<!ELEMENT urlset (url)+>
	<!ELEMENT url (loc, priority, lastmod, changefreq)*>
		<!ELEMENT loc (#PCDATA)>
		<!ELEMENT lastmod (#PCDATA)>
		<!ELEMENT priority (#PCDATA)>
		<!ELEMENT changefreq (#PCDATA)>
]>

<urlset>
	<url>
		<loc>http://bourelly.net/</loc>
		<priority>1</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://banque.bourelly.net/</loc>
		<priority>1</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/connexion/</loc>
		<priority>1</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/inscription/</loc>
		<priority>1</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>

	<url>
		<loc>http://bourelly.net/menu/gestion-compte-bancaire</loc>
		<priority>0.8</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/menu/listes-todo</loc>
		<priority>0.5</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/menu/projet-snid</loc>
		<priority>0.9</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/menu/autres-projets</loc>
		<priority>0.8</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/menu/a-mon-sujet</loc>
		<priority>0.7</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/menu/developpement-des-applications</loc>
		<priority>0.7</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
	<url>
		<loc>http://bourelly.net/menu/contactez-moi</loc>
		<priority>0.8</priority>
		<lastmod>2014-08-01</lastmod>
		<changefreq>monthly</changefreq>
	</url>
</urlset>